config/routes.rb
Rails.application.routes.draw do

  resources :xyzs
  root 'static_pages#home'
  resources :asanas do
    collection do
      get :search
    end
  end

  put '/xyzs', to: 'xyzs#qwert'
  devise_for :users
  get '/home', to: 'static_pages#home'
  get '/about', to: 'static_pages#about'
  get 'contact', to: 'static_pages#contact'
  get 'terms', to: 'static_pages#terms'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/asana.rb
class Asana < ApplicationRecord
	validates :name, :description, :image, presence: true
	searchable do
		text :name
	end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters, if: :devise_controller?

   # protect_from_forgery with: :exception

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :age])
  end
end

app/controllers/asanas_controller.rb
class AsanasController < ApplicationController
	include AsanaActivities
	before_action :authenticate_user!
	before_action :set_asan, only: [:edit, :update, :show, :destroy]

	def index
		@asans = Asana.order(:name)
	end
	
	def new
		@asan = Asana.new
	end

	def create
		if current_user.admin?
			@asan = Asana.create(asan_params)
			if @asan.save
				redirect_to @asan, success: "Asana Created Successfully"
			else
				render "new"
			end
		else
			redirect_to asanas_path
			flash[:error] = "You are not authorised to perform this action."
		end
	end

	def search
		@asanas_searched = search_asana
	end

	def update
		if current_user.admin?
			if @asan.update(asan_params)
				redirect_to @asan, success: "Asana Updated Successfully"
			else
				render "edit"
			end
		else
			redirect_to asanas_path
			flash[:error] = "You are not authorised to perform this action."
		end
	end

	def destroy
		if current_user.admin?
			@asan.destroy
			redirect_to @asan, alert: "Asana Deleted Successfully"
		else
			redirect_to asanas_path
			flash[:error] = "You are not authorised to perform this action."
		end
	end

	private

	def set_asan
		@asan = Asana.find(params[:id])
	end
	def asan_params
		params.require(:asana).permit(:name, :description, :image)
	end
end

app/controllers/concerns/asana_activities.rb
module AsanaActivities
	def search_asana
	 	search = Sunspot.search(Asana) do 
								fulltext params[:search]
							end.results		
	end
end							

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end

  def terms
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def bootstrap_class_for flash_type
    { success: "alert-success", error: "alert-danger", alert: "alert-warning", notice: "alert-info" }[flash_type] || flash_type.to_s
  end
	
	def flash_messages(opts = {})
    flash.each do |msg_type, message|
      concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type.to_sym)} fade in") do 
              concat content_tag(:button, 'x', class: "close", data: { dismiss: 'alert' })
              concat message 
            end)
    end
  end
end

app/helpers/asanas_helper.rb
module AsanasHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/asanas/_form.html.haml
= form_for @asan do |f|  
  = f.label :name  
  %br
  = f.text_field :name, size: "50"  
  %br
  = f.label :description   
  %br
  = f.text_area :description, size: "100x15"  
  %br
  = f.label :image   
  %br
  = f.text_field :image, size: "50"  
  %br
  %br
  = f.submit 

app/views/asanas/edit.html.haml
%h1 Edit Asana
= render 'form'

app/views/asanas/index.html.haml
%h1 All Yog Asanas
-@asans.each do |asan|
	.row.panel
		.col
			%h3 
			= link_to asan.name, asana_path(asan)
			%br
			%br
			= image_tag asan.image
		%br
		%br

app/views/asanas/new.html.haml
%h1 New Asana
= render 'form'

app/views/asanas/search.html.haml
.block
  .secondary-navigation
  .content
    - if params[:search].blank? || @asanas_searched.blank?
      #search_error
        %h2
          Sorry no matching results for keyword '#{params[:search]}'
        %br
        %br
        %br
        - @asanas_searched = Asana.all
        - @asanas_searched.each do |asana|
          %p
            = link_to asana.name, asana_path(asana)
          =image_tag(asana.image)
          %br
          %br
    - else
      %h2.title
        All articles containing keyword '#{params[:search]}'
      %br
      - @asanas_searched.each do |asana|
        %p
          = link_to asana.name, asana_path(asana)
        =image_tag(asana.image)
        %br
        %hr

app/views/asanas/show.html.haml
%h1 
	= best_in_place @asan, :name
%p
	= image_tag(@asan.image)
%p
	= best_in_place @asan, :description, as: :textarea
%p
-if current_user.admin? 
	= link_to "Edit", edit_asana_path(@asan) 
	|
	= link_to "Delete", asana_path(@asan), method: :delete

app/views/layouts/_navbar.html.haml
%nav.navbar.navbar-default.navbar-inverse.navbar-fixed-top
  .container-fluid
    / Brand and toggle get grouped for better mobile display
    .navbar-header
      %button.navbar-toggle.collapsed{"aria-expanded" => "false", "data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand{:href => "/"} YOGSRISHTI
    / Collect the nav links, forms, and other content for toggling
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      %ul.nav.navbar-nav
        %li.dropdown
          %a.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
            Asanas
            %span.caret
          %ul.dropdown-menu
            %li
              %a{:href => "/asanas"} Asanas
            %li
              =link_to "New", new_asana_path if current_user&.admin? && user_signed_in?
      %ul.nav.navbar-nav.navbar-right
        %li
          %a{:href => "/about"} About
        %li
          %a{:href => "/contact"} Contact
        - if user_signed_in?
          %li.dropdown
            %a.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
              = current_user.name
              %span.caret
            %ul.dropdown-menu
              %li= link_to "Profile", edit_user_registration_path
              %li.divider{:role => "separator"}
              %li= link_to "Logout",destroy_user_session_path, method: :delete
        - else
          %li
            %a{:href => "/users/sign_in"} Login

app/views/layouts/_search.html.haml
= form_tag search_asanas_path, :method => :get do
	= text_field_tag :search, params[:search]
	= submit_tag "Search"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title YogaApp
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/navbar'
    %center  
      .content
        .container
        -flash_messages
        .search_form{align: 'right'}
          =render 'layouts/search' unless controller_name.eql?('sessions') || controller_name.eql?('registrations')
        = yield
        %br
        %br

app/views/static_pages/about.html.haml
%h1 StaticPages#about
%p Find me in app/views/static_pages/about.html.erb

app/views/static_pages/contact.html.haml
%h1 StaticPages#contact
%p Find me in app/views/static_pages/contact.html.erb

app/views/static_pages/home.html.haml
%h1 Welcome to YogAsana  
%br     
=image_tag("https://www.artofliving.org/sites/www.artofliving.org/files/styles/section_page_carousel_image/public/achievement_carousel_image/Yoga---Homepage-02.jpg?itok=EMMz1jwD", hieght: 100)

app/views/static_pages/terms.html.haml
%h1 StaticPages#terms
%p Find me in app/views/static_pages/terms.html.erb